CREATE TABLE DIM_DATE (
    DATE_KEY NUMBER PRIMARY KEY,
    FULL_DATE DATE UNIQUE NOT NULL,
    DAY_NAME VARCHAR2(20) NOT NULL,
    DAY_NUMBER_IN_WEEK NUMBER
        CHECK (DAY_NUMBER_IN_WEEK BETWEEN 1 AND 7),
    DAY_NUMBER_IN_MONTH NUMBER
        CHECK (DAY_NUMBER_IN_MONTH BETWEEN 1 AND 31),
    WEEK_NUMBER NUMBER
        CHECK (WEEK_NUMBER BETWEEN 1 AND 53),
    MONTH_NUMBER NUMBER
        CHECK (MONTH_NUMBER BETWEEN 1 AND 12),
    MONTH_NAME VARCHAR2(20) NOT NULL,
    QUARTER_NUMBER NUMBER
        CHECK (QUARTER_NUMBER BETWEEN 1 AND 4),
    YEAR_NUMBER NUMBER NOT NULL,
    IS_WEEKEND CHAR(1) DEFAULT 'N'
        CHECK (IS_WEEKEND IN ('Y','N')),
    FISCAL_MONTH NUMBER,
    FISCAL_QUARTER NUMBER,
    FISCAL_YEAR NUMBER
);
