CREATE TABLE DIM_CONTENT (
    CONTENT_KEY NUMBER PRIMARY KEY,
    CONTENT_ID VARCHAR2(50) UNIQUE NOT NULL,
    TITLE VARCHAR2(300) NOT NULL,
    CONTENT_TYPE VARCHAR2(50)
        CHECK (CONTENT_TYPE IN ('MOVIE','SERIES','DOCUMENTARY')),
    GENRE VARCHAR2(100) NOT NULL,
    SUB_GENRE VARCHAR2(100),
    RELEASE_YEAR NUMBER(4)
        CHECK (RELEASE_YEAR >= 1900),
    LANGUAGE VARCHAR2(50) DEFAULT 'English',
    DURATION_MINUTES NUMBER
        CHECK (DURATION_MINUTES > 0),
    MATURITY_RATING VARCHAR2(20) DEFAULT 'PG',
    DIRECTOR VARCHAR2(200),
    CAST_MEMBERS VARCHAR2(1000),
    COUNTRY_OF_ORIGIN VARCHAR2(100),
    IMDB_RATING NUMBER(3,1)
        CHECK (IMDB_RATING BETWEEN 0 AND 10),
    CONTENT_STATUS VARCHAR2(30) DEFAULT 'AVAILABLE'
        CHECK (CONTENT_STATUS IN ('AVAILABLE','REMOVED')),
    LOAD_DATE DATE DEFAULT SYSDATE,
    CREATED_TS TIMESTAMP DEFAULT SYSTIMESTAMP
);
