CREATE TABLE DIM_DEVICE (
    DEVICE_KEY NUMBER PRIMARY KEY,
    DEVICE_ID VARCHAR2(100) UNIQUE NOT NULL,
    DEVICE_TYPE VARCHAR2(50) NOT NULL,
    DEVICE_BRAND VARCHAR2(100),
    DEVICE_MODEL VARCHAR2(100),
    OS_NAME VARCHAR2(100),
    OS_VERSION VARCHAR2(50),
    APP_VERSION VARCHAR2(50),
    SCREEN_RESOLUTION VARCHAR2(50),
    NETWORK_TYPE VARCHAR2(50) DEFAULT 'WiFi',
    IS_SMART_DEVICE CHAR(1) DEFAULT 'Y'
        CHECK (IS_SMART_DEVICE IN ('Y','N')),
    CREATED_TS TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);
