CREATE TABLE DIM_USER (
    USER_KEY NUMBER PRIMARY KEY,
    USER_ID VARCHAR2(50) UNIQUE NOT NULL,
    FIRST_NAME VARCHAR2(100) NOT NULL,
    LAST_NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(200) UNIQUE NOT NULL,
    GENDER VARCHAR2(20) DEFAULT 'Other'
        CHECK (GENDER IN ('Male','Female','Other')),
    DATE_OF_BIRTH DATE,
    AGE_GROUP VARCHAR2(30),
    COUNTRY VARCHAR2(100) NOT NULL,
    STATE VARCHAR2(100),
    CITY VARCHAR2(100),
    ZIP_CODE VARCHAR2(20),
    LANGUAGE_PREF VARCHAR2(50) DEFAULT 'English',
    SUBSCRIPTION_TYPE VARCHAR2(50) DEFAULT 'Basic',
    ACCOUNT_STATUS VARCHAR2(30) DEFAULT 'ACTIVE'
        CHECK (ACCOUNT_STATUS IN ('ACTIVE','SUSPENDED','CANCELLED')),
    CREATED_DATE DATE DEFAULT SYSDATE NOT NULL,
    LAST_LOGIN_DATE DATE,
    IS_ACTIVE CHAR(1) DEFAULT 'Y'
        CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_TS TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_TS TIMESTAMP DEFAULT SYSTIMESTAMP
);
