CREATE TABLE FACT_RECOMMENDATION (
    RECOMMENDATION_KEY NUMBER PRIMARY KEY,
    USER_KEY NUMBER NOT NULL,
    CONTENT_KEY NUMBER NOT NULL,
    DATE_KEY NUMBER NOT NULL,

    RECOMMENDATION_MODEL VARCHAR2(100) NOT NULL,

    RECOMMENDATION_SCORE NUMBER(8,4) DEFAULT 0
        CHECK (RECOMMENDATION_SCORE BETWEEN 0 AND 1),

    RANK_POSITION NUMBER DEFAULT 1
        CHECK (RANK_POSITION > 0),

    CLICKED_FLAG CHAR(1) DEFAULT 'N'
        CHECK (CLICKED_FLAG IN ('Y','N')),

    WATCHED_FLAG CHAR(1) DEFAULT 'N'
        CHECK (WATCHED_FLAG IN ('Y','N')),

    CREATED_TS TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT FK_FR_USER
        FOREIGN KEY (USER_KEY)
        REFERENCES DIM_USER(USER_KEY),

    CONSTRAINT FK_FR_CONTENT
        FOREIGN KEY (CONTENT_KEY)
        REFERENCES DIM_CONTENT(CONTENT_KEY),

    CONSTRAINT FK_FR_DATE
        FOREIGN KEY (DATE_KEY)
        REFERENCES DIM_DATE(DATE_KEY)
);
