CREATE TABLE DIM_REGION (
    REGION_KEY NUMBER PRIMARY KEY,
    REGION_ID VARCHAR2(50) UNIQUE NOT NULL,
    COUNTRY VARCHAR2(100) NOT NULL,
    REGION_NAME VARCHAR2(100) NOT NULL,
    STATE_PROVINCE VARCHAR2(100),
    CITY VARCHAR2(100),
    TIMEZONE VARCHAR2(100) DEFAULT 'UTC',
    CURRENCY_CODE VARCHAR2(10) DEFAULT 'USD',
    MARKET_SEGMENT VARCHAR2(50),
    ACTIVE_FLAG CHAR(1) DEFAULT 'Y'
        CHECK (ACTIVE_FLAG IN ('Y','N')),
    CREATED_TS TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);
