
CREATE TABLE FACT_SUBSCRIPTION (
    SUBSCRIPTION_KEY NUMBER PRIMARY KEY,
    USER_KEY NUMBER NOT NULL,
    REGION_KEY NUMBER NOT NULL,
    DATE_KEY NUMBER NOT NULL,

    PLAN_NAME VARCHAR2(50) DEFAULT 'Basic' NOT NULL,

    PLAN_PRICE NUMBER(10,2) DEFAULT 0
        CHECK (PLAN_PRICE >= 0),

    BILLING_CYCLE VARCHAR2(20) DEFAULT 'MONTHLY'
        CHECK (BILLING_CYCLE IN ('MONTHLY','YEARLY')),

    PAYMENT_METHOD VARCHAR2(50),

    SUBSCRIPTION_STATUS VARCHAR2(30) DEFAULT 'ACTIVE'
        CHECK (SUBSCRIPTION_STATUS IN ('ACTIVE','CANCELLED','PAUSED')),

    START_DATE DATE DEFAULT SYSDATE NOT NULL,
    END_DATE DATE,

    AUTO_RENEWAL_FLAG CHAR(1) DEFAULT 'Y'
        CHECK (AUTO_RENEWAL_FLAG IN ('Y','N')),

    CREATED_TS TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT FK_FS_USER
        FOREIGN KEY (USER_KEY)
        REFERENCES DIM_USER(USER_KEY),

    CONSTRAINT FK_FS_REGION
        FOREIGN KEY (REGION_KEY)
        REFERENCES DIM_REGION(REGION_KEY),

    CONSTRAINT FK_FS_DATE
        FOREIGN KEY (DATE_KEY)
        REFERENCES DIM_DATE(DATE_KEY)
);
