
CREATE TABLE FACT_STREAMING_EVENT (
    EVENT_KEY NUMBER PRIMARY KEY,
    USER_KEY NUMBER NOT NULL,
    CONTENT_KEY NUMBER NOT NULL,
    DEVICE_KEY NUMBER NOT NULL,
    REGION_KEY NUMBER NOT NULL,
    DATE_KEY NUMBER NOT NULL,

    EVENT_TYPE VARCHAR2(100) NOT NULL,

    EVENT_TIMESTAMP TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    STREAM_QUALITY VARCHAR2(50) DEFAULT 'HD',

    NETWORK_LATENCY_MS NUMBER DEFAULT 0
        CHECK (NETWORK_LATENCY_MS >= 0),

    BUFFER_TIME_SEC NUMBER DEFAULT 0
        CHECK (BUFFER_TIME_SEC >= 0),

    ERROR_CODE VARCHAR2(50),

    SESSION_ID VARCHAR2(100) NOT NULL,

    CREATED_TS TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT FK_FSE_USER
        FOREIGN KEY (USER_KEY)
        REFERENCES DIM_USER(USER_KEY),

    CONSTRAINT FK_FSE_CONTENT
        FOREIGN KEY (CONTENT_KEY)
        REFERENCES DIM_CONTENT(CONTENT_KEY),

    CONSTRAINT FK_FSE_DEVICE
        FOREIGN KEY (DEVICE_KEY)
        REFERENCES DIM_DEVICE(DEVICE_KEY),

    CONSTRAINT FK_FSE_REGION
        FOREIGN KEY (REGION_KEY)
        REFERENCES DIM_REGION(REGION_KEY),

    CONSTRAINT FK_FSE_DATE
        FOREIGN KEY (DATE_KEY)
        REFERENCES DIM_DATE(DATE_KEY)
);
